# Generated by Django 5.0 on 2023-12-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
