# Generated by Django 5.0 on 2023-12-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projeto_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='categoria',
            field=models.CharField(choices=[('B', 'Back-end'), ('F', 'Front-end'), ('D', 'DevOps'), ('S', 'Full-Stack')], default='F', max_length=1),
        ),
    ]
